Feature/service slot dto
SanctuaryTeam/diablo4trading-be pull request #48
Opened 2023-09-15 18:14 UTC by Sparky-Kitty

2023-09-15 18:17 UTC, Sparky-Kitty commented on src/auth/jwt/jwt.strategy.ts
I forgot this. I'll remove this change when I return home!

2023-09-15 19:04 UTC, d4search requested changes
👍👍

2023-09-15 19:04 UTC, d4search commented on src/users/user.dto.ts
> +    name?: string;
🤔😔

What do you think of changing the Dtos to interfaces? I've gone ahead and added some suggestions to this comment:

```tsx
import { User } from './users.entity';

export interface UserDto {
    id?: number;
    discordName: string;
    discordId?: string;
    email?: string;
    battleNetTag: string;
    vouchScore?: number;
    vouchRating?: number;
}

interface FromEntityOptions {
    hideDiscriminator?: boolean;
}

const formatBattleNetTag = (tag: string, hideDiscriminator?: boolean): string => {
    return hideDiscriminator ? tag.split('#')[0] : tag;
}

export const fromEntity = (entity: User, options: FromEntityOptions = {}): UserDto => {
    const { hideDiscriminator } = options;
    const { discordName, battleNetTag, vouchCalculation } = entity;
    const vouchScore = vouchCalculation?.score || 0;
    const vouchRating = vouchCalculation?.rating || 0;

    return {
        discordName,
        battleNetTag: formatBattleNetTag(battleNetTag, hideDiscriminator),
        vouchScore,
        vouchRating,
    };
}
```

Then say we are in `service.dto.ts` or any other file that references this interface.

```tsx
import { UserDto, fromEntity as userDtoFromEntity } from '../users/user.dto';
import { ServiceSlot } from './service-slots/service-slots.entity'; // Update this path as needed
import { IService } from './service.interface'; // Assuming you've named your interface IService
import { Service } from './services.entity';

export interface ServiceDto extends IService {
    id: number;
    realmType: string;
    title: string;
    content: string;
    user: UserDto;
    userId: number;
    tags: number;
    maxAcceptedSlots: number;
    slots: ServiceSlot[]; // Consider creating a ServiceSlotDto if needed
    bumpedAt: Date;
    createdAt: Date;
    updatedAt: Date;
    updatedBy: string;
    deleted: boolean;
}

export const fromEntity = (entity: Service): ServiceDto => {
    const {
        id, realmType, title, content, userId, tags, 
        maxAcceptedSlots, slots, bumpedAt, createdAt, 
        updatedAt, updatedBy, deleted, user
    } = entity;

    const userDto = user ? userDtoFromEntity(user) : undefined;

    return {
        id,
        realmType,
        title,
        content,
        userId,
        tags,
        maxAcceptedSlots,
        slots, // TODO: Use DTO
        bumpedAt,
        createdAt,
        updatedAt,
        updatedBy,
        deleted,
        user: userDto
    };
}
```

This is untested, not sure if we need to include the `extends IService` or `IUser`. But to me this approach seems cleaner. 

What do you think?

2023-09-15 19:04 UTC, d4search commented on src/services/service-slots/service-slots.dto.ts
> +        dto.service = ServiceDto.fromEntity(entity.service);
I think this should be an FromEntityOption, so we don't end up with circular properties if we include slots on the service etc. It may not be, but I guess we would want to remove the slots from the service, or figure that out too.

2023-09-17 19:33 UTC, Sparky-Kitty commented on src/users/user.dto.ts
> +    name?: string;
I like this. It feels more concise and less trial and error to make edge cases work.

2023-09-17 19:51 UTC, d4search commented on src/auth/auth.module.ts
> +            signOptions: { expiresIn: '30 days' },
I think the syntax is 30d

2023-09-17 19:51 UTC, d4search commented on src/services/service-slots/service-slots.controller.ts
> +        console.log('here');
Remove consoile log

2023-09-17 19:54 UTC, Sparky-Kitty commented on src/services/service-slots/service-slots.dto.ts
> +        dto.service = ServiceDto.fromEntity(entity.service);
It looks like you can do either:
![image](https://github.com/SanctuaryTeam/diablo4trading-be/assets/60945689/7c057221-656e-4707-abac-e99888cf2a78)

2023-09-17 19:54 UTC, Sparky-Kitty commented on src/auth/auth.module.ts
> +            signOptions: { expiresIn: '30 days' },
It looks like you can use days or d:
![image](https://github.com/SanctuaryTeam/diablo4trading-be/assets/60945689/b306bf33-da9d-4d5c-a04a-0979bc19ad83)

2023-09-17 19:55 UTC, Sparky-Kitty commented on src/auth/auth.module.ts
> +            signOptions: { expiresIn: '30 days' },
Changed just in case.

2023-09-17 21:01 UTC, d4search commented on src/services/service.dto.ts
> +export interface ServiceDto extends IService {
So do we need the extends here?

2023-09-17 21:02 UTC, d4search commented on src/services/service-slots/service-slots.service.ts
>          if (typeof id === 'number') {
Where we able to keep these functions?

2023-09-17 21:20 UTC, Sparky-Kitty commented on src/services/service-slots/service-slots.service.ts
>          if (typeof id === 'number') {
Yep. Just added back.

2023-09-17 23:55 UTC, d4search commented on src/services/service-slots/service-slots.controller.ts
> +        @Query('userId', OptionalParseIntPipe) userId?: number,
Possibly an enumeration attack could occur, but it depends if we care or not.

2023-09-17 23:58 UTC, d4search commented on src/services/service.interface.ts
> +    slots: ServiceSlotDto[];
Where are these implemented? If they are implemented against the entity then I don't think we need to use DTOs but just the other interfaces. These are also a bit redundant, I forget why we are using them.

2023-09-17 23:58 UTC, d4search approved these changes

2023-09-18 00:00 UTC, Sparky-Kitty commented on src/services/service-slots/service-slots.controller.ts
> +        @Query('userId', OptionalParseIntPipe) userId?: number,
Should we check against req.user with that request model?

2023-09-18 00:04 UTC, Sparky-Kitty commented on src/services/service.interface.ts
> +    slots: ServiceSlotDto[];
I deleted them, and the entities crashed the build for missing the reference to implement the iService

2023-09-18 01:19 UTC, merged