Feature/uuids and dtos
SanctuaryTeam/diablo4trading-be pull request #57
Opened 2023-09-20 04:55 UTC by Sparky-Kitty

2023-09-20 04:57 UTC, Sparky-Kitty commented
Still having issues with "unable to find matching" result that does exist, but we are close!

2023-09-21 02:17 UTC, d4search requested changes

2023-09-21 02:17 UTC, d4search commented on src/services/service-slots/service-slots.service.ts
> +        console.log(slotUuid);
Remove console log.

2023-09-21 03:44 UTC, d4search commented on src/services/service-slots/service-slots.service.ts
> +                    .where('service.uuid = :serviceId', { serviceId: slot.service?.uuid })
How can the service not have a uuid?

2023-09-21 03:44 UTC, d4search commented on src/services/service-slots/service-slots.service.ts
> +                    .where('client_user_id = :clientId', { clientId: slot.client?.id })
How can the client not have an id?

2023-09-21 03:49 UTC, merged